version: "2"
services:
  web:
    container_name: web
    restart: always
    build: ./web/dashboard
    ports:
      - "8000:8000"
    depends_on:
      - server
  server:
    container_name: server
    restart: always
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  doc:
    container_name: doc
    image: linuxserver/nginx
    ports:
      - "80:80"
    volumes:
       - ./docs:/config
